name: Update Atlas

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unciv-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Download Unciv
        run: |
          unciv_url=$(curl -sL https://api.github.com/repos/yairm210/Unciv/releases/latest | grep -o "http.*Unciv.jar")
          wget -q -O Unciv.jar "$unciv_url"

      - name: Update texture atlas
        run: |
          java -jar Unciv.jar mod-ci

      - name: Remove Unciv
        run: rm Unciv.jar

      - name: Commit updated atlas
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update texture atlas"
          file_pattern: "game.png game.atlas Atlases.json"
