name: Update Atlas

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-atlas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Download Unciv
        run: |
          wget -q \
            https://github.com/yairm210/Unciv/releases/latest/download/Unciv.jar \
            -O Unciv.jar

          ls -lh Unciv.jar

      - name: Run Unciv mod-ci
        run: |
          java -jar Unciv.jar mod-ci

      - name: Show changed files
        run: |
          git status --short

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Unciv texture atlas"
            git push
          fi
